config/routes.rb
Rails.application.routes.draw do
  resources :rounds
  resources :players

  root 'rounds#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
	has_many :round_players
	has_many :rounds, through: :round_players
	
	validates :name, presence: true, length: { maximum: 12 }
	validates :money, presence: true

	before_update :player_state

	def self.end_of_day
		t = Time.new
		buff_t = t.hour
		buff_t *= 60
		buff_t += t.min
		buff_t = (24*60) - buff_t
		if (t.hour == 23 && t.minute >= 59) || (t.hour == 0 && t.minute <= 1)
			players = Player.all
			players.each do |pl|			
				pl.money += 10000
				pl.active = true
				pl.save
			end
		end
		self.delay(:run_at => buff_t.minutes.from_now).end_of_day
	end

	def player_state
		if self.money <= 0
			self.active = false
		elsif self.money > 0
			self.active = true
		end
		true
	end
end

app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :player
	belongs_to :round

	def self.obtain_round_results(round, player)
		rn = Random.new
		if player.money <= 1000 && player.money > 0
			ba = player.money
		else
			buff = rn.rand(0..1)
			if buff == 0
				ba = (player.money*8)/100
			else
				ba = (player.money*15)/100
			end
		end
	    buff = rn.rand(0..100)
	    if buff <= 2
	      bv = "verde"
	    elsif buff <= 51
	      bv = "rojo"
	    else
	      bv = "negro"
	    end
	    return [ba,bv]
	end
end

app/models/round.rb
class Round < ActiveRecord::Base
	has_many :round_players
	has_many :players, through: :round_players

	def self.new_round
	    buff = rand(101)
	    if buff <= 2
	    	return Round.new(result: "green")
	    elsif buff <= 51
	    	return Round.new(result: "red")
	    else 
	    	return Round.new(result: "black")
	    end
	end

	def self.play
		round = Round.new_round
	    round.save
	    players = Player.all
	    players.where(active: true).each do |pl|
	      round.round_players.create(player: pl)
	    end
	    round.round_players.each do |rp|
	      if rp.player.active == true
	        rp.bet_name = rp.player.name
	        rva = RoundPlayer.obtain_bets(rp.player)
	        rp.bet_amount = rva[0]
	        wl = RoundPlayer.obtain_results(rva[1], round.result)
	        if wl == 15
	          rp.bet_result = "Big winner"
	        elsif wl == 2
	          rp.bet_result = "Winner"
	        else
	          rp.bet_result = "Looser"
	        end
	        rp.bet_value = rva[1]
	        rp.player.money = (rp.player.money + rva[0]*(wl - 1))
	        rp.round_money = rp.player.money
	        if rp.player.money <= 0
	          rp.player.active = false
	        end
	        rp.player.save
	        rp.save
	      end
	    end	
	    self.delay(:run_at => 3.minutes.from_now).play
	end	
end

app/models/round_player.rb
class RoundPlayer < ActiveRecord::Base
	belongs_to :player
	belongs_to :round

	def self.obtain_bets(player)
		if player.money <= 1000 && player.money > 0
			ba = player.money			
		else
			buff = rand(2)
			if buff == 0
				ba = (player.money*8)/100
			else
				ba = (player.money*15)/100
			end
		end
	    buff = rand(101)
	    if buff <= 2
	      bv = "green"
	    elsif buff <= 51
	      bv = "red"
	    else
	      bv = "black"
	    end
	    return [ba, bv]
	end

	def self.obtain_results(plv, res_color)
		if res_color == "green"
			if res_color == plv
				return 15
			else
				return 0
			end
		elsif res_color == plv
			return 2
		else
			return 0
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      begin
        @player = Player.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to players_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :money)
    end
  
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: [:show, :edit, :update, :destroy]

  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.includes(:round_players).all
  end

=begin
  # GET /rounds/new
  def new
    Round.play
    redirect_to rounds_url
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(round_params)

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1
  # PATCH/PUT /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: 'Round was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
=end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      #@round = Round.find(params[:id])
      redirect_to rounds_url
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:result)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NNTarea</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/_form.html.erb
  <%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="field">
    <%= f.label :Active %><br>
    <%= f.number_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Money</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.money %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>
<%= link_to 'Back to Rounds', rounds_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @player.money %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Rounds</h3>

<%= link_to 'See Players', players_path %>

<% @rounds.each do |r| %>
  <table>
    <thead>
      <tr>
        <th>Round: <%= r.id   %></th>
        <th>Color: <%= r.result%></th>
      </tr>
    </thead>
    <table>
      <% i = 0 %>
      <% r.round_players.each do |rp| %>
        <tr>          
          <% if rp.player_id != nil%>
            <td><%= "Player: #{rp.bet_name}" %></td>
            <td><%= "Color: #{rp.bet_value}" %></td>
            <td><%= "Bet: #{rp.bet_amount}" %></td>
            <% if rp.bet_result == "Big winner" %>
              <% br = rp.bet_amount*14 %>
              <td><%= "Won: #{br}" %></td>
            <% elsif rp.bet_result == "Winner" %>
              <td><%= "Won: #{rp.bet_amount}" %></td>
            <% else %>
              <td><%= "Lost: #{rp.bet_amount}" %></td>
            <% end %>
            <td><%= "Player Money: #{rp.round_money}" %></td>
            <% i += 1 %>
          <% end %>          
        </tr>
      <% end %>
      <tr>
        <% if i == 0 %>
              <%= "No active players" %>
        <% end %>
      </tr>
    </table>
  </table>
<% end %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>